version: "{build}"

skip_tags: true

cache:
  - c:\x86_64-pc-msys -> .appveyor.yml

#environment:
#  matrix:
#  - win: 32
#  - win: 64

# TODO: cygwin, 32+64bit
#configuration:
#  - release
#  - debug

clone_depth: 1

clone_folder: C:\projects\%APPVEYOR_PROJECT_NAME%

# see https://www.appveyor.com/docs/build-environment/#mingw-msys-cygwin
install:
  - cinst wget -y
  - set PATH=C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin;%PATH%;C:\MinGW\msys\1.0\bin
  # git bash conflicts with MinGW makefiles, esp. the space in 'Program Files'
  - set "PATH=%PATH:C:\Program Files\Git\usr\bin;=%"
  - cd C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64
  # some tools just call make
  - copy bin\mingw32-make.exe bin\make.exe
  # XXX hack, otherwise fails on -lc
  - copy x86_64-w64-mingw32\lib\libntdll.a x86_64-w64-mingw32\lib\libc.a
  #- dir C:\MinGW\bin
  #- dir C:\MinGW\msys\1.0\bin
  #- cd C:\projects\%APPVEYOR_PROJECT_NAME%
  - cd C:\projects\clisp
  - ps: |
      $package_commit = git rev-parse --short --verify "HEAD^{commit}"
      $package_version = (Get-Content "version.sh")
      $package_version = "2.49.50+"
      $package_iteration = "$package_iteration${env:appveyor_build_number}.$package_commit"
      Update-AppveyorBuild -Version "clisp-${env:appveyor_repo_branch}-$package_version-$package_iteration"

  # fails with libtool
  - wget -q --no-check-certificate https://ftp.gnu.org/gnu/libsigsegv/libsigsegv-2.11.tar.gz
  - tar xfz libsigsegv-2.11.tar.gz
  - cd libsigsegv-2.11
  - patch -p1 -i ../utils/libsigsegv-win64.patch
  - sh -c "CC=x86_64-w64-mingw32-gcc-6.3.0 ./configure --prefix=/c/x86_64-pc-msys && make all install" || true
  - cd ..

  # libffcall still todo on windows
  - wget -q --no-check-certificate https://haible.de/bruno/gnu/libffcall-1.13-20170225.tar.gz
  - tar xfz libffcall-1.13-20170225.tar.gz
  - patch -p0 -i utils/libffcall-1.13-20170225-funbegin.patch
  - cd libffcall-1.13-20170225
  - sh -c "CC=x86_64-w64-mingw32-gcc-6.3.0 ./configure --prefix=/c/x86_64-pc-msys && make all install" || true
  - cd ..

  #- ps: |
  #    $clispdir = "${env:appveyor_build_version}-win64"
  #    cd C:\projects\clisp\src
  #    md "$clispdir"
  #    md "${clispdir}\clisp"
  #    md "${clispdir}\clisp\bin"
  #    $builddir = "C:\projects\clisp\build\${env:configuration}-llvm-${env:llvm}"
  #    Write-Output "Build dir is ${builddir}"
  #    copy $builddir\clisp.* "${clispdir}\clisp\bin"
  #    copy -recurse packages "${clispdir}\packages"
  #    7z a -tzip "C:\projects\clisp\${clispdir}.zip" "${clispdir}"

build: off

test_script:
  - set PATH=C:\MinGW\msys\1.0\bin;%PATH%;
  - bash -c "CC=x86_64-w64-mingw32-gcc-6.3.0 ./configure --ignore-absence-of-libsigsegv --with-libsigsegv-prefix=/c/x86_64-pc-msys && cd src && make -j4 all && make check" || type src\clisp.rc

artifacts:
  - path: 'clisp-*.zip'

deploy:
  # On branche `release`, deploy (and publish) artifacts
  # to the clisp-win projects on Bintray.
  - provider: BinTray
    username: clisp-buildbot-1
    api_key:
        secure: ""
    subject: clisp
    repo: clisp-win
    package: clisp-release
    version: $(appveyor_build_version)
    on:
        branch: release
        configuration: release
    publish: true
  